obj-y				+= cpu.o irq.o time.o clock.o \
				   l2mem.o dma.o gpio.o devices.o \
					lib_freq.o \
					lib_mmu.o \
					lib_gpio.o \
					lib_lcd.o \
					l2.o
			

obj-$(CONFIG_AK88_PWM)	+= pwm.o

# Power Management support

obj-$(CONFIG_AK88_PM)		+= pm.o sleep.o

# Machin support

obj-y				+= boards.o
