obj-$(CONFIG_MTD_NAND_AK98) += ak98-nandflash.o
	ak98-nandflash-objs := ak98_nand.o wrap_nand.o nand_control.o communicate.o  

obj-$(CONFIG_MTD_NAND_TEST) += nand_char.o
obj-$(CONFIG_MTD_DOWNLOAD_MODE) += nand_char.o
